#!/usr/bin/env bash
# Valentina Curiosity Web Monitor — no_agent cron script (v4)
# Checks HN + Arxiv for AI/agent developments
# Simple, reliable — captures raw data, no fancy parsing
#
# 3-tier sync: root → profile → rebirth
# Created: 2026-06-26

set -euo pipefail

PROFILE_DIR="$HOME/.hermes/profiles/valentina"
OUTPUT_DIR="$PROFILE_DIR/knowledge/discoveries"
TIMESTAMP=$(date +%Y%m%d_%H%M)
RANDOM_SUFFIX=$(head /dev/urandom | md5sum | head -c 8)
OUTPUT_FILE="$OUTPUT_DIR/web-intel-$TIMESTAMP-$RANDOM_SUFFIX.md"

mkdir -p "$OUTPUT_DIR"

# === 1. Fetch HN front page ===
HN_DATA=$(timeout 30 curl -sL "https://r.jina.ai/https://news.ycombinator.com/" 2>/dev/null || echo "_(HN fetch failed)_")
HN_FLAT=$(echo "$HN_DATA" | tr '\n' ' ')

# Count stories: count "points by" occurrences
HN_COUNT=$(echo "$HN_FLAT" | grep -oP '\d+ points by \[' | wc -l 2>/dev/null || echo 0)

# Extract AI-relevant stories: lines containing AI keywords
HN_AI=$(echo "$HN_DATA" | grep -iE 'ai|agent|llm|gpt|claude|openai|anthropic|mythos|sol|glm|deepseek|fugu|wayfinder|workweave|router|orca|montage|mcp' 2>/dev/null || true)
HN_AI_COUNT=$(echo "$HN_AI" | grep -c '\[.\+\]' 2>/dev/null || echo 0)

# === 2. Fetch Arxiv AI recent papers ===
ARXIV_DATA=$(timeout 30 curl -sL "https://r.jina.ai/https://arxiv.org/list/cs.AI/recent" 2>/dev/null || echo "_(Arxiv fetch failed)_")
ARXIV_TITLES=$(echo "$ARXIV_DATA" | grep -E '^Title:' 2>/dev/null | head -20)
ARXIV_COUNT=$(echo "$ARXIV_TITLES" | wc -l 2>/dev/null || echo 0)

# === 3. Write discovery log ===
{
  echo "# Curiosity Web Monitor — $(date '+%Y-%m-%d %H:%M')"
  echo ""
  echo "## Hacker News — Front Page"
  echo "### Stories detected: $HN_COUNT"
  echo ""
  echo "\`\`\`"
  echo "$HN_DATA" | head -40
  echo "\`\`\`"
  echo ""
  echo "### AI/Agent-Relevant Mentions: $HN_AI_COUNT"
  echo ""
  [ -n "$HN_AI" ] && echo "$HN_AI" || echo "(none)"
  echo ""
  echo "---"
  echo ""
  echo "## Arxiv cs.AI — Recent Papers"
  echo ""
  echo "$ARXIV_TITLES"
  echo ""
  echo "### Agent-Specific Papers"
  echo "$ARXIV_TITLES" | grep -iE 'agent|language model|prompt|multi-agent' 2>/dev/null || echo "(none)"
  echo ""
  echo "---"
  echo ""
  echo "## Summary"
  echo "- Scanned: $(date '+%Y-%m-%d %H:%M:%S')"
  echo "- HN stories: $HN_COUNT"
  echo "- Arxiv papers: $ARXIV_COUNT"
  echo ""
  echo "*Generated by curiosity-web-monitor.sh v4*"
} > "$OUTPUT_FILE"

echo "[$(date '+%H:%M')] Curiosity Monitor ✓ — $HN_COUNT HN stories — $(basename "$OUTPUT_FILE")"
