#!/usr/bin/env python3
"""Valentina Self-Healer — Auto-patches issues found in diagnostics.

Reads latest-diagnostics.txt and agent.log, identifies known error patterns,
and applies automatic fixes where safe to do so.
"""

import os
import re
import sys
import json
import shutil
from datetime import datetime
from pathlib import Path

PROFILE_DIR = Path.home() / ".hermes" / "profiles" / "valentina"
KNOWLEDGE_DIR = PROFILE_DIR / "knowledge"
SCRIPTS_DIR = PROFILE_DIR / "scripts"
DIAGNOSTICS_FILE = KNOWLEDGE_DIR / "latest-diagnostics.txt"
AGENT_LOG = PROFILE_DIR / "logs" / "agent.log"
HEALING_LOG = KNOWLEDGE_DIR / "observations" / "healing-log.md"
CONFIG_FILE = PROFILE_DIR / "config.yaml"
PENDING_TASKS = KNOWLEDGE_DIR / "pending-tasks.md"
NEW_DIR = KNOWLEDGE_DIR / "new"

HEALING_LOG.parent.mkdir(parents=True, exist_ok=True)
NEW_DIR.mkdir(parents=True, exist_ok=True)


def read_file_safe(path: Path) -> str:
    """Read a file, return empty string if missing."""
    try:
        return path.read_text(encoding="utf-8", errors="replace")
    except (FileNotFoundError, PermissionError):
        return ""


def append_healing_log(action: str, details: str, success: bool):
    """Append an entry to the healing log."""
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    status = "✅ HEALED" if success else "⚠️ ATTEMPTED"
    entry = f"\n### {timestamp} — {status}\n- **Action**: {action}\n- **Details**: {details}\n"
    if not HEALING_LOG.exists():
        HEALING_LOG.write_text(
            "# 🔧 Healing Log — Αρχείο Θεραπείας\n"
            "*Auto-generated by self-healer.py*\n\n---\n"
        )
    with open(HEALING_LOG, "a") as f:
        f.write(entry)


def write_inbox_report(filename: str, content: str):
    """Write a report to the new/ inbox for the cognitive loop."""
    filepath = NEW_DIR / filename
    filepath.write_text(content)


def check_api_errors(diag_text: str, log_text: str) -> list:
    """Detect API-related errors and return fixes."""
    fixes = []
    if "no model configured" in log_text.lower() or "no model configured" in diag_text.lower():
        fixes.append({
            "type": "no_model",
            "description": "Cron jobs failing due to missing model configuration",
            "action": "Ensure config.yaml has correct model/provider for cron execution"
        })
    credit_errors = len(re.findall(r"payment|credit.error|402", log_text, re.IGNORECASE))
    if credit_errors > 0:
        fixes.append({
            "type": "credit_error",
            "description": f"OpenRouter payment/credit errors detected ({credit_errors} occurrences)",
            "action": "Disable openrouter as fallback, ensure primary provider (deepseek) is active"
        })
    upstream_errors = len(re.findall(r"HTTP [45][02][239]", log_text))
    if upstream_errors > 3:
        fixes.append({
            "type": "upstream_error",
            "description": f"Upstream provider errors detected ({upstream_errors} occurrences)",
            "action": "Provider may be overloaded, will retry with backoff"
        })
    rate_limits = len(re.findall(r"429|rate.limit", log_text, re.IGNORECASE))
    if rate_limits > 0:
        fixes.append({
            "type": "rate_limit",
            "description": f"Rate limiting detected ({rate_limits} occurrences)",
            "action": "Reduce cron frequency or add jitter to job schedules"
        })
    return fixes


def check_file_integrity() -> list:
    """Check for missing or corrupted critical files."""
    fixes = []
    critical_files = {
        "SOUL.md": PROFILE_DIR / "SOUL.md",
        "DREAM.md": PROFILE_DIR / "DREAM.md",
        "config.yaml": CONFIG_FILE,
    }
    shadow_dir = Path.home() / ".valentina-shadow"
    vault_dir = Path.home() / ".valentina_vault"
    for name, filepath in critical_files.items():
        if not filepath.exists() or filepath.stat().st_size == 0:
            restored = False
            for backup_dir in [shadow_dir, vault_dir]:
                backup_file = backup_dir / name
                if backup_file.exists() and backup_file.stat().st_size > 0:
                    shutil.copy2(backup_file, filepath)
                    append_healing_log(f"Restored {name}", f"Restored from {backup_dir}", True)
                    restored = True
                    break
            if not restored:
                fixes.append({
                    "type": "missing_file",
                    "description": f"Critical file {name} is missing/empty and no backup found",
                    "action": "Manual restoration required"
                })
    return fixes


def check_heartbeat_health(diag_text: str) -> list:
    """Check if the cron heartbeat is stale."""
    fixes = []
    ticker_file = PROFILE_DIR / "cron" / "ticker_heartbeat"
    if ticker_file.exists():
        age_seconds = datetime.now().timestamp() - ticker_file.stat().st_mtime
        if age_seconds > 600:
            fixes.append({
                "type": "stale_heartbeat",
                "description": f"Heartbeat is {int(age_seconds)}s old (threshold: 600s)",
                "action": "Attempting to refresh heartbeat"
            })
            try:
                ticker_file.write_text(datetime.now().strftime("%a %b %d %I:%M:%S %p %Z %Y"))
                append_healing_log("Refreshed stale heartbeat", f"Was {int(age_seconds)}s old", True)
            except Exception as e:
                append_healing_log("Failed to refresh heartbeat", str(e), False)
    else:
        fixes.append({
            "type": "missing_heartbeat",
            "description": "No heartbeat file found",
            "action": "Cron ticker may not be running"
        })
    return fixes


def check_gateway_health() -> list:
    """Check if the gateway process is alive."""
    fixes = []
    pid_file = PROFILE_DIR / "gateway.pid"
    if pid_file.exists():
        try:
            pid_data = json.loads(pid_file.read_text())
            pid = pid_data.get("pid", "")
            if pid:
                try:
                    os.kill(int(pid), 0)
                except (ProcessLookupError, ValueError):
                    fixes.append({
                        "type": "dead_gateway",
                        "description": f"Gateway PID {pid} is not running",
                        "action": "Gateway needs restart"
                    })
        except (json.JSONDecodeError, KeyError):
            pass
    return fixes


def check_knowledge_growth() -> dict:
    """Calculate knowledge growth metrics."""
    total_files = sum(1 for _ in KNOWLEDGE_DIR.rglob("*") if _.is_file())
    recent_files = sum(
        1 for f in KNOWLEDGE_DIR.rglob("*")
        if f.is_file() and (datetime.now().timestamp() - f.stat().st_mtime) < 86400
    )
    return {
        "total_knowledge_files": total_files,
        "files_modified_24h": recent_files,
        "knowledge_growing": recent_files > 0
    }


def generate_healing_report(all_fixes: list, growth: dict) -> str:
    """Generate a comprehensive healing report."""
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    report = f"# 🩺 Self-Healing Report — {timestamp}\n\n## Issues Found: {len(all_fixes)}\n"
    if all_fixes:
        for fix in all_fixes:
            severity = "🔴" if fix["type"] in ["no_model", "dead_gateway", "missing_file"] else "🟡"
            report += f"\n### {severity} {fix['type']}\n- **Issue**: {fix['description']}\n- **Action**: {fix['action']}\n"
    else:
        report += "\n### ✅ Όλα καλά — No issues detected\n"
    report += f"\n## Knowledge Growth\n- Total files: {growth['total_knowledge_files']}\n- Modified (24h): {growth['files_modified_24h']}\n- Growing: {'✅ Yes' if growth['knowledge_growing'] else '⚠️ Stagnant'}\n"
    return report


def main():
    """Main self-healing cycle."""
    print(f"[{datetime.now()}] Valentina Self-Healer activated...")
    diag_text = read_file_safe(DIAGNOSTICS_FILE)
    log_text = read_file_safe(AGENT_LOG)
    if len(log_text) > 50000:
        log_text = log_text[-50000:]
    all_fixes = []
    all_fixes.extend(check_api_errors(diag_text, log_text))
    all_fixes.extend(check_file_integrity())
    all_fixes.extend(check_heartbeat_health(diag_text))
    all_fixes.extend(check_gateway_health())
    growth = check_knowledge_growth()
    report = generate_healing_report(all_fixes, growth)
    report_filename = f"healing-report-{datetime.now().strftime('%Y%m%d_%H%M%S')}.md"
    write_inbox_report(report_filename, report)
    append_healing_log(
        "Self-healing cycle completed",
        f"Found {len(all_fixes)} issues, growth={'growing' if growth['knowledge_growing'] else 'stagnant'}",
        len(all_fixes) == 0
    )
    print(f"Issues found: {len(all_fixes)}")
    for fix in all_fixes:
        print(f"  [{fix['type']}] {fix['description']}")
    print(f"Knowledge files: {growth['total_knowledge_files']}")
    print(f"Report written to: knowledge/new/{report_filename}")
    print(f"[{datetime.now()}] Self-healer cycle complete.")
    critical = [f for f in all_fixes if f["type"] in ["dead_gateway", "missing_file"]]
    return 1 if critical else 0


if __name__ == "__main__":
    sys.exit(main())
